# Ceph User: admin/USER_NAME (Used by Ceph RBD StorageClass)
# ceph auth get-or-create client.${CEPH_USER} mon 'profile rbd' osd 'profile rbd pool=${CEPH_POOL}' mgr 'allow rw'
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: #CEPH_NAMESPACE#
stringData:
  userID: #CEPH_USER#
  userKey: #CEPH_USER_KEY#
