# Ceph User: admin/USER_NAME (Used by Ceph RBD StorageClass)
# ceph auth get-or-create client.${CEPH_USER} mon 'profile rbd' osd 'profile rbd pool=${CEPH_POOL}' mgr 'allow rw'
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph
stringData:
  userID: u18-k8s
  userKey: AQAQ9ANhErvoLxAA7Fl961zBrpU6tPmbkC6iTQ==
