name: '#MASTER_HOSTNAME#'
data-dir: /var/lib/etcd
wal-dir: /var/lib/etcd/wal
snapshot-count: 5000
heartbeat-interval: 100
election-timeout: 1000
quota-backend-bytes: 0
listen-peer-urls: 'https://#MASTER_IP#:2380'
listen-client-urls: 'https://#MASTER_IP#:2379,http://127.0.0.1:2379'
max-snapshots: 3
max-wals: 5
cors:
initial-advertise-peer-urls: 'https://#MASTER_IP#:2380'
advertise-client-urls: 'https://#MASTER_IP#:2379'
discovery:
discovery-fallback: 'proxy'
discovery-proxy:
discovery-srv:
initial-cluster: '#MASTER_HOSTNAME_0#=https://#MASTER_IP_0#:2380,#MASTER_HOSTNAME_1#=https://#MASTER_IP_1#:2380,#MASTER_HOSTNAME_2#=https://#MASTER_IP_2#:2380'
initial-cluster-token: 'etcd-k8s-cluster'
initial-cluster-state: 'new'
strict-reconfig-check: false
enable-v2: true
enable-pprof: true
proxy: 'off'
proxy-failure-wait: 5000
proxy-refresh-interval: 30000
proxy-dial-timeout: 1000
proxy-write-timeout: 5000
proxy-read-timeout: 0
client-transport-security:
  cert-file: '#KUBE_CERT_PATH#/etcd/etcd.pem'
  key-file: '#KUBE_CERT_PATH#/etcd/etcd-key.pem'
  client-cert-auth: true
  trusted-ca-file: '#KUBE_CERT_PATH#/etcd/etcd-ca.pem'
  auto-tls: true
peer-transport-security:
  cert-file: '#KUBE_CERT_PATH#/etcd/etcd.pem'
  key-file: '#KUBE_CERT_PATH#/etcd/etcd-key.pem'
  peer-client-cert-auth: true
  trusted-ca-file: '#KUBE_CERT_PATH#/etcd/etcd-ca.pem'
  auto-tls: true
debug: false
log-package-levels:
log-outputs: [default]
force-new-cluster: false
