apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: latest
    created: 2021-02-05T13:28:16.728034918Z
    description: CSI NFS Driver for Kubernetes
    digest: aa12e668649d4f9fc979389618992c1195847feff048dab0f2413ef02fbcc837
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: 2021-02-05T13:28:16.728270519Z
    description: CSI NFS Driver for Kubernetes
    digest: f537a133eaa965f1c053ffac130f82c9b2b624e1f8bd42937c9c48818464eaac
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: 2021-02-05T13:28:16.727677516Z
