apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumesnapshot-pvc2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ceph-fs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
