# 3. Deploy ConfigMap for CSI plugins
---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "#CEPH_CLUSTER_ID#",
        "monitors": [
          "#CEPH_MON_IP_0#:6789",
          "#CEPH_MON_IP_1#:6789",
          "#CEPH_MON_IP_2#:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: #CEPH_NAMESPACE#
