# ceph user: admin (Used by CephFS StorageClass)
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQDW8gNhCiu6NBAAEBSKPtQOMnplCPUX2K70Cg==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQDW8gNhCiu6NBAAEBSKPtQOMnplCPUX2K70Cg==
