# ceph user: admin (Used by CephFS StorageClass)
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: #CEPH_NAMESPACE#
stringData:
  # Required for statically provisioned volumes
  userID: #CEPH_USER#
  userKey: #CEPH_USER_KEY#

  # Required for dynamically provisioned volumes
  adminID: #CEPH_USER#
  adminKey: #CEPH_USER_KEY#
