# 1:clusterID 可以如下命令来获取
#   ceph mon dump | grep fsid
#   ceph -s | grep id
# 2:替换此处的 clusterID 和 monitors
# 3:namespace 根据你的生产环境

---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "#CEPH_CLUSTER_ID#",
        "monitors": [
          "#CEPH_MON_IP_0#:6789",
          "#CEPH_MON_IP_1#:6789",
          "#CEPH_MON_IP_2#:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: #CEPH_NAMESPACE#
