# 1:替换此处的 userID 和 userKey，userID 默认是 kubernetes
# 2:获取 userKey：
#   ceph auth print-key client.kubernetes
# 3:namespace 取决于你的生产环境

---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: #CEPH_NAMESPACE#
stringData:
  userID: #CEPH_USER#
  userKey: #CEPH_USER_KEY#
