# 1:替换此处的 userID 和 userKey，userID 默认是 kubernetes
# 2:获取 userKey：
#   ceph auth print-key client.kubernetes
# 3:namespace 取决于你的生产环境

---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph
stringData:
  userID: c7-k8s
  userKey: AQCwbYlg1cE4OBAAvmgMo0tOnVhe4IFoM5MnbQ==
